export const TOGGLE_PLAYER_STATE = 'TOGGLE_PLAYER_STATE';
export const INCREASE_HOME_SCORE = 'INCREASE_HOME_SCORE';
export const DECREASE_HOME_SCORE = 'DECREASE_HOME_SCORE';
export const INCREASE_AWAY_SCORE = 'INCREASE_AWAY_SCORE';
export const DECREASE_AWAY_SCORE = 'DECREASE_AWAY_SCORE';
